// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qiuflxuahobebdyncops.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpdWZseHVhaG9iZWJkeW5jb3BzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0OTMwNjMsImV4cCI6MjA2ODA2OTA2M30.0g9xIrZWK0LNU9Q6R9DWXF5gTf4SZB4uqZugZZGMMqE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});